version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - mongo_data:/data/db


  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9000
      - "DatabaseSettings__ConnectionString=mongodb://catalog:27017"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    ports:
      - "9000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - catalogdb